server:
  port: 60019

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/db25312
    username: dbid253
    password: dbpass253
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update        # 개발 초기엔 update가 편함, 배포 시 none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  jackson:
    time-zone: Asia/Seoul
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  ai:
    server:
      base-url: https://cherlyn-unforeboded-unmarvellously.ngrok-free.dev
      timeout-ms: 15000

security:
  jwt:
    secret: "cWhA8zvDKu3lHvUEAjb6mzpr5xO55uDtaJ6SNeOXSsx"
    access-token-validity-ms: 3600000   # 1 hour
kma:
  weather:
    base-url: https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
    service-key: a56696519f570c142f52fbcf25f09fe4ed4a4298943100eb63cd687ddfc687ba
    timeout-ms: 3000
    enabled: true